name: Jekyll Workshop
paginate: 8
paginate_path: "SampleJekyllTheme/page:num"
permalink: /:categories/:title/
markdown: kramdown
highlighter: rouge
url: https://dawid93.github.io/SampleJekyllTheme

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap